version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: ReloHome
    ports:
      - "65432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  logs:
    image: parseable/parseable
    restart: always
    environment:
      P_USERNAME: tigrulya
      P_PASSWORD: adminyopta
    command: ["parseable", "local-store"]
    ports:
      - "8000:8000"

  redis:
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 120 1
    volumes:
      - ./cache-data:/data
