rootProject.name = "ReloHome"
include("flat-ads-fetchers")
include("flat-ads-fetchers:fetcher-listam")
include("flat-ads-fetchers:fetcher-base")
include("flat-ads-fetchers:fetcher-ssge")
include("flat-ads-handler")
include("flat-ads-notifier")
include("flat-ads-notifier:notifier-base")
include("flat-ads-notifier:notifier-telegram")
include("flat-ads-base")
include("flat-ads-demo")
include("flat-ads-docker")
