ktor:
    application:
        modules:
            - exe.tigrulya.relohome.handler.ApplicationKt.module
    deployment:
        port: 8080
        sslPort: 8443
    security:
        ssl:
            keyStore: '/opt/relohome/conf/keystore.jks'
            keyAlias: ssl
            keyStorePassword: 123456
            privateKeyPassword: 123456