ktor:
    application:
        modules:
            - exe.tigrulya.relohome.handler.ApplicationKt.module
    deployment:
        port: 8080
        sslPort: 8443
    security:
        ssl:
            keyStore: 'D:\IdeaProjects\ReloHome\flat-ads-demo\src\main\resources\keystore.jks'
            keyAlias: ssl
            keyStorePassword: 123456
            privateKeyPassword: 123456