# Use root/example as user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: ReloHome
    ports:
      - "65432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  kafka:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

  handler:
    image: relohome/flat-ads-handler:0.3
    command:
      - "-Djava.util.logging.config.file=/opt/relohome/conf/logging.properties"
    ports:
      - "8443:8443"
    volumes:
      - ./conf:/opt/relohome/conf
    depends_on:
      - postgres
      - kafka

  fetcher-ssge:
    image: relohome/fetcher-ssge:0.3
    volumes:
      - ./conf:/opt/relohome/conf
      - ./:/opt/relohome/data
    depends_on:
      - handler

  notifier-tg:
    image: relohome/notifier-telegram:0.3
    environment:
      - BOT_TOKEN=${TG_BOT_TOKEN}
    volumes:
      - ./conf:/opt/relohome/conf
    depends_on:
      - handler
