# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: ReloHome
    ports:
      - "65432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data